apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: blog
build:
  local:
    push: false
  artifacts:
    - image: oluwakemifasae/blog_comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: oluwakemifasae/blog_event_bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: oluwakemifasae/blog_moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: oluwakemifasae/blog_posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: oluwakemifasae/blog_query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: oluwakemifasae/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
